Add librespot initial-volume option (#276)
* Adds initial-volume option.

* Adds initial-volume option.

* add constraints to ensure values stay within the valid range of 0-100

* Fixed translation issues.

* validate that the initial-volume value is within the valid range (0-100) before passing it to librespot.

* Improved documentation.

* Prettified Code!

* Update DOCS.md 

Removed irrelevant description about behavior with different backends

* Update DOCS.md

* Update en.yaml

* Update hu.yaml

* Update it.yaml

---------

Co-authored-by: spoetnik <spoetnik@users.noreply.github.com>
Co-authored-by: Franck Nijhof <git@frenck.dev>

diff --git a/spotify/rootfs/etc/services.d/spotifyd/run b/spotify/rootfs/etc/services.d/spotifyd/run
--- a/spotify/rootfs/etc/services.d/spotifyd/run
+++ b/spotify/rootfs/etc/services.d/spotifyd/run
@@ -9,11 +9,21 @@ declare name
 declare password
 declare username
 declare autoplay
+declare initial-volume
 
 bashio::log.info 'Starting the Spotify daemon...'
 
 # Bitrate
 options+=(--bitrate $(bashio::config 'bitrate'))
+
+# Initial Volume
+initial_volume=$(bashio::config 'initial-volume')
+if ! [[ "$initial_volume" =~ ^[0-9]+$ ]] || [ "$initial_volume" -lt 0 ] || [ "$initial_volume" -gt 100 ]; then
+    bashio::log.warning "Invalid initial-volume value: $initial_volume. Using default."
+    initial_volume=50
+fi
+options+=(--initial-volume "$initial_volume")
+
 
 # Device name
 name=$(bashio::config 'name')
