validate that the initial-volume value is within the valid range (0-100) before passing it to librespot.

diff --git a/spotify/rootfs/etc/services.d/spotifyd/run b/spotify/rootfs/etc/services.d/spotifyd/run
--- a/spotify/rootfs/etc/services.d/spotifyd/run
+++ b/spotify/rootfs/etc/services.d/spotifyd/run
@@ -16,7 +16,13 @@ bashio::log.info 'Starting the Spotify daemon...'
 options+=(--bitrate $(bashio::config 'bitrate'))
 
 # Initial Volume
-options+=(--initial-volume $(bashio::config 'initial-volume'))
+initial_volume=$(bashio::config 'initial-volume')
+if ! [[ "$initial_volume" =~ ^[0-9]+$ ]] || [ "$initial_volume" -lt 0 ] || [ "$initial_volume" -gt 100 ]; then
+    bashio::log.warning "Invalid initial-volume value: $initial_volume. Using default."
+    initial_volume=50
+fi
+options+=(--initial-volume "$initial_volume")
+
 
 # Device name
 name=$(bashio::config 'name')
